# Generated by Django 3.1.2 on 2020-10-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='campaign.Tag'),
        ),
    ]
