# Generated by Django 3.1.2 on 2020-10-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20201006_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='titre',
            field=models.CharField(max_length=50),
        ),
    ]
