# Generated by Django 3.1.2 on 2020-10-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20201009_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='titre',
            new_name='title',
        ),
    ]
